# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Измаилов Павел Алексеевич

Группа: 317

In [66]:
import numpy as np
import pandas as pd

In [67]:
from collections import defaultdict
from functools import reduce
import re

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [68]:
[n for n in range(0, 101) if n%7 == 0 and n%5 != 0]

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [69]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [70]:
def sort_tokens(s):
    return ','.join(sorted(s.split(',')))
print(sort_tokens("ночь,фонарь,улица"))
print(sort_tokens("Павел,Алексеевич,Измаилов"))
print(sort_tokens("Математические,методы,распознавания,образов"))

ночь,улица,фонарь
Алексеевич,Измаилов,Павел
Математические,методы,образов,распознавания


#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [71]:
def remove_duplicates(a):
    return sorted(list(set(a)))

In [72]:
#Тест
lst = ["ночь", "улица", "фонарь", "аптека", "аптека", "улица", "фонарь"]
remove_duplicates(lst)

['аптека', 'ночь', 'улица', 'фонарь']

#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [73]:
list(map(lambda x: x.lower(), ["abCDefg", "HIjkL"]))

['abcdefg', 'hijkl']

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [74]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [75]:
d = defaultdict(int)
print(d)
d['abc'] += 1
print(d)
d['xxx']
print(d)

defaultdict(<class 'int'>, {})
defaultdict(<class 'int'>, {'abc': 1})
defaultdict(<class 'int'>, {'xxx': 0, 'abc': 1})


In [76]:
def word_counts(text):
    word_lst_lst = list(map(lambda l: l.split(" "), text))
    word_lst = reduce(lambda l1, l2: l1+l2, word_lst_lst)
    dict = defaultdict(int)
    for word in word_lst:
        dict[word] += 1
    for key, val in dict.items():
        print(key, val)

In [77]:
#Тест
s = ['ночь улица фонарь аптека', 'аптека улица фонарь']
word_counts(s)

фонарь 2
аптека 2
улица 2
ночь 1


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Удалите из него все специальные символы и цифры. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [78]:
from urllib.request import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

In [79]:
raw_text[1000:1100]

'r five\r\nchildren in only two rooms. The father and mother spent their evenings\r\nin reading aloud to '

In [80]:
processed_text = re.findall(r"[\w']+", raw_text)
processed_text = list(map(lambda x: x.lower(), processed_text))
from collections import defaultdict
word_dict = defaultdict(int)
for word in processed_text:
    word_dict[word] += 1
sorted_word_list = sorted(word_dict, key=(lambda word: word_dict[word]))
print("Слова, которые встречаются один раз: ", sorted_word_list[:20])
print("Самые часто встречающиеся слова: ", sorted_word_list[-20:])

Слова, которые встречаются один раз:  ['appropriately', 'thunderstorm', "buch's", 'leave_', 'unheeded', 'vulgarise', 'concubine', 'club', 'guardian', 'profile', 'server', 'sip', 'jack', 'feign', 'accompanying', 'baggage', 'succumbed', 'confronting', 'centre', 'consequently']
Самые часто встречающиеся слова:  ['she', 'for', 'with', 'not', 'but', 'her', 'at', 'his', 'was', 'that', 'it', 'in', 'you', 'of', 'i', 'a', 'he', 'to', 'and', 'the']


## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [81]:
max_lst = []
for i in range (0, 1000):
    A = np.random.randn(10, 10)
    B = np.random.randn(10, 10)
    C = A.dot(B)
    max_lst.append(np.max(C))
print(np.mean(max_lst))
print(np.percentile(max_lst, 95))

8.41570744909
11.9458632826


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [82]:
numbers = np.random.poisson(5, (1000,))
answer = np.bincount(numbers)
print(answer)

[  5  27  91 134 198 167 143 116  50  39  17   7   3   1   1   1]


#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [83]:
def inverse_bincount(a):
    x = np.arange(a.size)
    return np.repeat(x, a)

inverse_bincount(answer)

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [84]:
def scale(x):
    B = x - x.mean(axis=0)
    var = np.sqrt(np.sum(B**2, axis=0) / B.shape[0])
    var[var < 1e-12] = 1
    return B / var
    
A = np.array([[1, 2],[1, 3]])
B = np.random.randn(10, 10)
A_sc = scale(A)
B_sc = scale(B)
print(A_sc)
print(np.var(B_sc, axis=0), np.linalg.norm(np.mean(B_sc, axis=0)))

[[ 0. -1.]
 [ 0.  1.]]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.] 1.90182664399e-16


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [ ]:
A = np.random.randn(10, 10) + 10
print("Определитель: ", np.linalg.det(A))
print("След: ", np.trace(A))
print("Минимальный и максимальный элемент: ", np.min(A), np.max(A))
# print("Спектральная норма: ",np.sqrt(np.max(np.linalg.eigvals(A.dot(A.T)))))
print("Спектральная норма: ", np.linalg.norm(A, ord=2))
print("Норма Фробениуса: ", np.linalg.norm(A))
print("Собственные числа: ", np.linalg.eigvals(A))
print("Обратная матрица: ", np.linalg.inv(A))

Определитель:  8978.23821352
След:  104.417683625
Минимальный и максимальный элемент:  7.70463714229 12.0331177461
Спектральная норма:  100.736623783
Норма Фробениуса:  101.062850875
Собственные числа:  [  1.00652829e+02+0.j           8.27182976e-01+2.91082976j
   8.27182976e-01-2.91082976j  -1.24406937e+00+1.25255219j
  -1.24406937e+00-1.25255219j   5.93138934e-02+0.65919121j
   5.93138934e-02-0.65919121j   1.18997792e+00+1.40767153j
   1.18997792e+00-1.40767153j   2.10004407e+00+0.j        ]
Обратная матрица:  [[  1.53284586e-01  -7.03712872e-02   5.07040697e-02   1.46135385e-01
    3.49317713e-01  -1.58071386e-01  -1.49580449e-02   8.97854376e-02
    3.24389758e-02  -5.61166058e-01]
 [  2.60437486e+00  -2.24235690e-02   7.05320401e-01   8.20229397e-01
    1.90149282e-01  -4.22878807e-01  -6.72750188e-02  -1.67851655e+00
    4.35600072e-01  -2.40361563e+00]
 [ -1.00940059e+00  -7.10451418e-02  -2.99023888e-01  -1.58595331e-01
   -6.79913465e-02   9.32246669e-02   1.98895007e-01   4.8

## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

## Ответы

### Вопрос 1

Самая частая причина отмены рейса:  Weather

### Вопрос 2

Средняя дистанция:  726.387029425 миль

Наибольшая дистанция:  4962 миль

Наименьшая дистанция:  11 миль

### Вопрос 3

Номера рейсов: 4988, 5572

Даты: 15.05.2008, 10.08.2008

Средняя дистанция для рейса 4998 составляет 770 миль

Средняя дистанция для рейса 5572 составляет 384 миль

### Вопрос 4

Больше всего вылетов было произведено из аэропорта 'Atl' в городе Атланта 

###Вопрос 5

Аэропорт, имеющий наибольшее значение данного показателя — 'SJU'

### Вопрос 6

Аэропорт, в котором доля задержек была наибольшей — 'DAL'

## Код

In [ ]:
data = pd.read_csv('2008.csv.bz2')

###Вопрос 1

In [ ]:
answer_1 = ((data[data.Cancelled != 0]).CancellationCode).mode()[0]

In [ ]:
code_to_str = {'A': "Carrier", 'B': "Weather", 'C': "Nationa air system", 'D': "Security"}

In [ ]:
print("Самая частая причина отмены рейса: ", code_to_str[answer_1])

###Вопрос 2

In [ ]:
print("Средняя дистанция: ", (data.Distance).mean())
print("Наибольшая дистанция: ", (data.Distance).max())
print("Наименьшая дистанция: ", (data.Distance).min())

###Вопрос 3

In [ ]:
suspicious_flights = data[data.Distance == 11]
suspicious_flights[['Month', 'DayofMonth', 'FlightNum', 'UniqueCarrier']]

In [ ]:
((data[np.logical_and(data.FlightNum == 4988, data.UniqueCarrier == "OH")]).Distance).describe()

In [ ]:
((data[np.logical_and(data.FlightNum == 5572, data.UniqueCarrier == "OH")]).Distance).describe()

### Вопрос 4

In [ ]:
data.columns

In [ ]:
(data.Origin).mode()[0]

### Вопрос 5

In [ ]:
d_origin = (data.groupby('Origin'))

In [ ]:
d_airtime = d_origin.AirTime

In [ ]:
means = (d_airtime.aggregate(np.mean))

In [ ]:
means.argmax()

In [ ]:
means.max()

In [ ]:
means['SJU']

###Вопрос 6

In [ ]:
d_filtered = (d_origin.filter(lambda x: len(x) > 1000))

In [ ]:
d_delayed = d_filtered[d_filtered["DepDelay"] > 0].groupby("Origin").size()

In [ ]:
d_all = d_filtered.groupby("Origin").size()

In [ ]:
np.argmax(d_delayed / d_all)